### ISSUE TITLE
Trying to use octopufs - copyFolder with spark 2.4.5

### ISSUE THREAD

**Issue by RodrigoPombo** [procter-gamble-oss/octopufs#4]
Hello,

Tried to use octopufs to copy folderContent in spark 2.4.5 (DBR: 6.4). 
Got this error message: 

org.apache.spark.SparkException: Job aborted due to stage failure: Task 6 in stage 1.0 failed 4 times, most recent failure: Lost task 6.3 in stage 1.0 (TID 36, 10.139.64.5, executor 1): java.io.IOException: java.lang.RuntimeException: java.lang.NoSuchMethodException: org.apache.spark.util.GlobalHadoopConfiguration.<init>()

Steps to reproduce:
import jar file through databricks ui

set: 
spark.conf.set("spark.speculation","false")
implicit val s = spark
implicit val c = spark.sparkContext.hadoopConfiguration

run:
import com.pg.bigdata.octopufs.fs._
import com.pg.bigdata.octopufs.fs.Paths
DistributedExecution.copyFolder("/mnt/xxx","/mnt/xxx/yyy")

The same works fine with spark 2.4.4 (DBR:6.3).
I can import that specific class on another call:
import org.apache.spark.util.GlobalHadoopConfiguration

I even tried to change the dependencies on build.sbt to spark 2.4.5.

Is there anything we can change to make it work with spark 2.4.5?

Thanks

**Comment by JacekTokar** [comment]
It doesn't look like issue with spark version - it works on my local machine. It seems to be a problem with databricks runtime. 

Apparently spark returns different type after deserialization of Hadoop Configuration which is very weird. I am checking with Databricks, but this may end up as a ticket in their system.

I will keep you posted

**Comment by RodrigoPombo** [comment]
Hello,

re-tested and it works fine. Thanks!
